# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import fainens_pb2 as fainens__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in fainens_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class TransactionServiceStub(object):
    """Definisi layanan untuk manajemen transaksi
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddTransaction = channel.unary_unary(
                '/TransactionService/AddTransaction',
                request_serializer=fainens__pb2.AddTransactionRequest.SerializeToString,
                response_deserializer=fainens__pb2.AddTransactionResponse.FromString,
                _registered_method=True)
        self.GetTransactionsByType = channel.unary_unary(
                '/TransactionService/GetTransactionsByType',
                request_serializer=fainens__pb2.GetTransactionsByTypeRequest.SerializeToString,
                response_deserializer=fainens__pb2.GetTransactionsByTypeResponse.FromString,
                _registered_method=True)
        self.UpdateTransaction = channel.unary_unary(
                '/TransactionService/UpdateTransaction',
                request_serializer=fainens__pb2.UpdateTransactionRequest.SerializeToString,
                response_deserializer=fainens__pb2.UpdateTransactionResponse.FromString,
                _registered_method=True)
        self.DeleteTransaction = channel.unary_unary(
                '/TransactionService/DeleteTransaction',
                request_serializer=fainens__pb2.DeleteTransactionRequest.SerializeToString,
                response_deserializer=fainens__pb2.DeleteTransactionResponse.FromString,
                _registered_method=True)


class TransactionServiceServicer(object):
    """Definisi layanan untuk manajemen transaksi
    """

    def AddTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransactionsByType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransactionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTransaction,
                    request_deserializer=fainens__pb2.AddTransactionRequest.FromString,
                    response_serializer=fainens__pb2.AddTransactionResponse.SerializeToString,
            ),
            'GetTransactionsByType': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransactionsByType,
                    request_deserializer=fainens__pb2.GetTransactionsByTypeRequest.FromString,
                    response_serializer=fainens__pb2.GetTransactionsByTypeResponse.SerializeToString,
            ),
            'UpdateTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTransaction,
                    request_deserializer=fainens__pb2.UpdateTransactionRequest.FromString,
                    response_serializer=fainens__pb2.UpdateTransactionResponse.SerializeToString,
            ),
            'DeleteTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTransaction,
                    request_deserializer=fainens__pb2.DeleteTransactionRequest.FromString,
                    response_serializer=fainens__pb2.DeleteTransactionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TransactionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TransactionService(object):
    """Definisi layanan untuk manajemen transaksi
    """

    @staticmethod
    def AddTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TransactionService/AddTransaction',
            fainens__pb2.AddTransactionRequest.SerializeToString,
            fainens__pb2.AddTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransactionsByType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TransactionService/GetTransactionsByType',
            fainens__pb2.GetTransactionsByTypeRequest.SerializeToString,
            fainens__pb2.GetTransactionsByTypeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TransactionService/UpdateTransaction',
            fainens__pb2.UpdateTransactionRequest.SerializeToString,
            fainens__pb2.UpdateTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TransactionService/DeleteTransaction',
            fainens__pb2.DeleteTransactionRequest.SerializeToString,
            fainens__pb2.DeleteTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
